### ISSUE TITLE
啥时候弄成直接部署到LINUX系统上呗

### ISSUE THREAD

**Issue by haslong** [lilyhcn1/ExcelQuery#1]
# 最好下载后能直接部署的
方便我们小白测试~

**Comment by lilyhcn1** [comment]
我也就一小白，我出个教程，教你们怎么把这个部署到给你个服务器上吧。
什么docker，什么一键安装，我都不会。
你的回帖让我很激动啊，想到我自己的东西，也有人关注了，很开心

**Comment by lilyhcn1** [comment]
已更新虚拟主机的构建方法，欢迎测试，并提出宝贵意见！~
