### ISSUE TITLE
安装运行之后，点击新增按钮报错

### ISSUE THREAD

**Issue by huahuasichun** [lilyhcn1/ExcelQuery#3]
老师请问， 点击新增
![1567058185(1)](https://user-images.githubusercontent.com/52898848/63914136-df18de00-ca64-11e9-931f-b325a2eff202.jpg)
会报错，非法操作

**Comment by huahuasichun** [comment]
![1567058256(1)](https://user-images.githubusercontent.com/52898848/63914373-9a417700-ca65-11e9-9f59-9a3227eada9e.jpg)

还有一个就是，我把网址改为自己的ip，然后点击xlsm文件里面的手机填写网址、免密码查询、在线修改提示我都是
![1567058492(1)](https://user-images.githubusercontent.com/52898848/63914530-18058280-ca66-11e9-890f-ab27e31402c8.jpg)
![zhoabudao ](https://user-images.githubusercontent.com/52898848/63914656-7c284680-ca66-11e9-9523-51a1b91c5c32.jpg)

是不是因为我安装时候网站类型选择，选择的是互联网1型导致的啊

**Comment by huahuasichun** [comment]
![zhoabudao ](https://user-images.githubusercontent.com/52898848/63914656-7c284680-ca66-11e9-9523-51a1b91c5c32.jpg)

**Comment by huahuasichun** [comment]
还有最后一个问题就是，我现在有四张表，但是我想删除表，需要怎样操作呢
![1567058958(1)](https://user-images.githubusercontent.com/52898848/63914709-9d893280-ca66-11e9-8eeb-0157e6263291.jpg)

**Comment by huahuasichun** [comment]
> ![1567058256(1)](https://user-images.githubusercontent.com/52898848/63914373-9a417700-

**Comment by lilyhcn1** [comment]
问题很多啊，我发现都是我代码没写好的原因。
1. 第一个问题已修正，你可以下载最新版本，服务器源代码\App\Qwadmin  覆盖到对应位置即可。
2. excel也是bug,也可以下载最新版来修正
3. 这个功能暂时没有说明，你可以上传一个空的表格上去即可，不要写任何文字。

**Comment by huahuasichun** [comment]
嗯嗯，好的，我下个新版本，感谢您的回答。
