### ISSUE TITLE
非常好用，感谢 如何自动更新本地文件？

### ISSUE THREAD

**Issue by qxwo** [lilyhcn1/ExcelQuery#4]
选择自动下载就可以吗？

**Comment by qxwo** [comment]
只能查询姓名字段吗？如何查询别的字段呀?

**Comment by lilyhcn1** [comment]
自动下载可以通过python自动打开文件，再运行宏的方式。
只能显示查询一个字段，如果查不到，那会全局搜索。

**Comment by qxwo** [comment]
好像不会进行全局搜索呀，只能搜索一个字段，搜其他字段都不行，是姿势不对吗？
